context:
  version: 1.5.1

package:
  name: pyjpegls
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyjpegls/pyjpegls-${{ version }}.tar.gz
  sha256: d0fe09dfb7f75ce78e3b1e0519912a42f1827d68bbc3609652f4f8743c956025

build:
  script: ${{ PYTHON }} -m pip install .
  number: 0
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}

  host:
    - python
    - setuptools
    - cython
    - numpy >=2.0.0
    - pip

  run:
    - python
    - numpy >=2.0,<3

tests:
  - python:
      imports:
        - jpeg_ls
      pip_check: true 

about:
  summary: JPEG-LS for Python via CharLS C++ Library
  documentation: https://pydicom.github.io/pyjpegls
  homepage: https://github.com/pydicom/pyjpegls
  repository: https://github.com/pydicom/pyjpegls
  license: MIT
  license_file: license.txt

extra:
  recipe-maintainers:
    - jjjermiah
    - mrbean-bremen
    - scaramallion
